import { Application, StageInfo } from '../types';
import { STAGES_12 } from './brand';

function createStages(currentStageNum: number, timestamp: string): StageInfo[] {
  return STAGES_12.map(s => ({
    number: s.number,
    name: s.name,
    status: s.number < currentStageNum ? 'Completed' : s.number === currentStageNum ? 'In Progress' : 'Pending',
    updatedAt: timestamp,
  }));
}

const now = new Date().toISOString();

export const INITIAL_APPLICATIONS: Application[] = [
  {
    id: 'APP-2026-891042',
    customerName: 'Vikramaditya Sharma',
    customerPhone: '+91 98201 54321',
    customerEmail: 'vikram.sharma@gmail.com',
    city: 'Thane',
    state: 'Maharashtra',
    loanType: 'Home Loan',
    requestedAmount: 7500000,
    sanctionAmount: 7200000,
    disbursementAmount: 0,
    lenderPartner: 'HDFC Bank',
    assignedAssociateId: 'CB-LON-104',
    assignedAssociateName: 'Priya Patel',
    status: 'In Process',
    currentStage: 6,
    currentStageName: 'In-Principle Sanction Letter',
    stages: createStages(6, now),
    createdDate: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedDate: now,
    notes: 'In-principle sanction approved at 7.20% floating. Awaiting title search and TSR from panel advocate.',
  },
  {
    id: 'APP-2026-642190',
    customerName: 'Apex Precision Engineering Pvt Ltd',
    customerPhone: '+91 98190 77654',
    customerEmail: 'accounts@apexprecision.in',
    city: 'Navi Mumbai',
    state: 'Maharashtra',
    loanType: 'Working Capital',
    requestedAmount: 18000000,
    sanctionAmount: 15000000,
    disbursementAmount: 15000000,
    lenderPartner: 'ICICI Bank',
    assignedAssociateId: 'CB-DSA-501',
    assignedAssociateName: 'Suresh Kumar',
    status: 'Disbursed',
    currentStage: 11,
    currentStageName: 'Loan Agreement Signing & Disbursement',
    stages: createStages(11, now),
    createdDate: new Date(Date.now() - 14 * 86400000).toISOString(),
    updatedDate: now,
    notes: 'CC / OD limit of ₹1.5 Cr successfully sanctioned and disbursed into operative account.',
  },
  {
    id: 'APP-2026-784912',
    customerName: 'Sneha Kulkarni',
    customerPhone: '+91 97654 32189',
    customerEmail: 'sneha.kulkarni@yahoo.co.in',
    city: 'Pune',
    state: 'Maharashtra',
    loanType: 'Loan Against Property (LAP)',
    requestedAmount: 12000000,
    sanctionAmount: 11000000,
    disbursementAmount: 0,
    lenderPartner: 'Axis Bank',
    assignedAssociateId: 'CB-LON-104',
    assignedAssociateName: 'Priya Patel',
    status: 'In Process',
    currentStage: 4,
    currentStageName: 'Multi-Bank Evaluation & Login',
    stages: createStages(4, now),
    createdDate: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedDate: now,
    notes: 'Documents vetted. Logged with Axis Bank and SMFG India Credit for parallel rate evaluation.',
  },
  {
    id: 'APP-2026-412583',
    customerName: 'Rohit Anand Deshmukh',
    customerPhone: '+91 98230 45678',
    customerEmail: 'rohit.deshmukh@outlook.com',
    city: 'Mumbai',
    state: 'Maharashtra',
    loanType: 'Commercial Purchase',
    requestedAmount: 25000000,
    sanctionAmount: 23500000,
    disbursementAmount: 0,
    lenderPartner: 'State Bank of India',
    assignedAssociateId: 'CB-ADM-001',
    assignedAssociateName: 'Rajesh Sharma',
    status: 'In Process',
    currentStage: 8,
    currentStageName: 'Technical Valuation & Property Inspection',
    stages: createStages(8, now),
    createdDate: new Date(Date.now() - 8 * 86400000).toISOString(),
    updatedDate: now,
    notes: 'Commercial office suite in Bandra Kurla Complex. Technical engineer completed physical inspection yesterday.',
  },
  {
    id: 'APP-2026-921475',
    customerName: 'Meenakshi Sundaram',
    customerPhone: '+91 98450 12345',
    customerEmail: 'meenakshi.s@gmail.com',
    city: 'Thane',
    state: 'Maharashtra',
    loanType: 'Unsecured Business Loan',
    requestedAmount: 3500000,
    sanctionAmount: 3500000,
    disbursementAmount: 3500000,
    lenderPartner: 'Bajaj Finance',
    assignedAssociateId: 'CB-DSA-501',
    assignedAssociateName: 'Suresh Kumar',
    status: 'Disbursed',
    currentStage: 12,
    currentStageName: 'Post-Disbursement Documentation (PDD)',
    stages: createStages(12, now),
    createdDate: new Date(Date.now() - 21 * 86400000).toISOString(),
    updatedDate: now,
    notes: 'Fast-track collateral-free business loan disbursed. NACH mandate active.',
  },
  {
    id: 'APP-2026-538910',
    customerName: 'Kailash & Sons Logistics',
    customerPhone: '+91 98211 99887',
    customerEmail: 'contact@kailashlogistics.com',
    city: 'Bhiwandi',
    state: 'Maharashtra',
    loanType: 'Warehouse / Godown',
    requestedAmount: 32000000,
    sanctionAmount: 0,
    disbursementAmount: 0,
    lenderPartner: 'Tata Capital',
    assignedAssociateId: 'CB-LON-104',
    assignedAssociateName: 'Priya Patel',
    status: 'In Process',
    currentStage: 2,
    currentStageName: 'Application Form & File Login',
    stages: createStages(2, now),
    createdDate: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedDate: now,
    notes: 'Warehouse plot and PEB shed documents submitted. KYC and 3-year audited financial verification in progress.',
  },
];
